framework:
    messenger:
        reset_on_message: true

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            call_friend:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Component\Message\CallMessage': call_friend
